@endpoint=http://localhost:4000/api

### getAllRecipesWithAll
GET {{endpoint}}/recipes

### getOneRecipeById
GET {{endpoint}}/recipes/3

### getAllRecipesByCards
GET {{endpoint}}/recipes/cards

### getOneRecipeByCards
GET {{endpoint}}/recipes/cards/3


### getRecipesRandomly
GET {{endpoint}}/recipes/cards/random

### getAllMaterials
GET {{endpoint}}/materials

### getOneMaterialById
GET {{endpoint}}/materials/1
