BEGIN;

INSERT INTO "method" ("name", "description") VALUES ('Shaker', 'Cette méthode consiste à mélanger les ingrédients d''un cocktail dans un shaker avec de la glace, puis à secouer vigoureusement. Cela permet de bien intégrer les saveurs et de refroidir la boisson.'),
('Mélanger', 'Les ingrédients sont mélangés dans un verre à mélange avec de la glace, puis remués à l''aide d''une cuillère de bar. Cette méthode est utilisée pour les cocktails contenant principalement des spiritueux, afin d''éviter de trop diluer le mélange.'),
('Piler', 'On écrase des fruits, des herbes ou des sucres dans le fond du verre à l''aide d''un pilon pour libérer leurs arômes avant d''ajouter les autres ingrédients. Cette méthode est souvent utilisée pour les cocktails frais et fruités.'),
('Mixer', 'Les ingrédients sont mélangés avec de la glace dans un mixeur électrique. Cette méthode est idéale pour les cocktails glacés et les smoothies.'),
('Superposer', 'Les ingrédients sont versés doucement sur le dos d''une cuillère pour créer des couches distinctes. Cela crée un effet visuel attrayant et est souvent utilisé pour les shots ou les cocktails festifs.'),
('Direct', 'Les ingrédients sont directement ajoutés dans le verre de service sans mélange préalable. Cette méthode est souvent utilisée pour les cocktails simples ou les boissons servies sur glace.');

INSERT INTO "taste" ("type") VALUES ('Doux'),
('Salé'),
('Acidulé'),
('Amer'),
('Épicé'),
('Fruité'),
('Herbacé'),
('Floral'),
('Boisé'),
('Fumé'),
('Umammi'),
('Corsé');

INSERT INTO "glass" ("name", "capacity", "description", "url_image") VALUES ('Martini', 20, 'Verre en forme de cône avec un pied long et mince. Utilisé pour servir des cocktails comme le Martini, le Cosmopolitan, et d''autres cocktails "up" (servis sans glace).', 'martini_glass.webp'),
('Old fashioned', 25, 'Petit verre à fond épais, aussi appelé "rocks glass" ou "lowball". Utilisé pour les cocktails servis avec des glaçons comme l''Old Fashioned, le Negroni, et le Whiskey Sour.', 'old_fashioned_glass.webp'),
('Highball', 35, 'Grand verre cylindrique. Utilisé pour les cocktails servis avec beaucoup de glaçons et un grand volume de mixer, comme le Mojito et le Dark and Stormy.', 'highball_glass.webp'),
('Margarita', 30, 'Verre en forme de bol avec une large ouverture et un pied long. Utilisé principalement pour servir les Margaritas.', 'margarita_glass.webp'),
('Vin', 30, 'Verre à pied avec un bol large pour les vins rouges ou un bol plus petit pour les vins blancs. Utilisé pour servir le vin, mais aussi parfois pour certains cocktails à base de vin ou de champagne.', 'vin_glass.webp'),
('Flute', 20, 'Verre étroit et long avec un pied. Utilisé pour servir le champagne et les cocktails pétillants comme le Mimosa et le French 75.', 'flute_glass.webp'),
('Shooter', 5, 'Petit verre sans pied, utilisé pour servir des shots d''alcool pur ou des shooters.', 'shooter_glass.webp'),
('Digestif', 20, 'Verre à pied avec un bol large et un col étroit. Utilisé pour servir des spiritueux comme le brandy et le cognac, permettant de concentrer les arômes.', 'digestif_glass.webp'),
('Mule', 25, 'Tasse en cuivre avec une anse. Utilisé principalement pour servir les Moscow Mules.', 'mule_glass.webp'),
('Hurricane', 35, 'Verre courbé et allongé, en forme de lampe à ouragan. Utilisé pour les cocktails tropicaux et fruités comme le Hurricane et la Piña Colada.', 'hurricane_glass.webp'),
('Irish Coffee', 20, 'Verre avec une base solide et une anse. Utilisé pour servir des boissons chaudes comme l''Irish Coffee.', 'irish_coffee_glass.webp'),
('Tiki', 35, 'Mug souvent décoré de motifs polynésiens. Utilisé pour les cocktails tiki comme le Mai Tai et le Zombie.', 'tiki_glass.webp');

INSERT INTO "ustensil" ("name", "description", "use", "alternative", "url_image_1", "url_image_2", "url_image_3") VALUES ('Shaker', 'Outil essentiel pour mélanger les ingrédients d''un cocktail avec de la glace. Il existe trois types principaux : le shaker Boston (deux pièces, généralement un verre et une tin), le shaker Cobbler (trois pièces, avec un couvercle et une passoire intégrée) et le shaker continental (deux pièces comme le boston, géréralement en argent il est souvent utilisé dans les palaces).', 'Remplissez le shaker de glace, ajoutez les ingrédients, secouez vigoureusement pendant environ 10-15 secondes, puis filtrez dans un verre.', 'Si vous ne disposez pas de shaker, vous pouvez utiliser une boîte hermétique de type Tupperware pour obtenir des résultats similaires.', 'shaker_1.webp', 'shaker_2.webp', 'shaker_3.webp'),
('Bar spoon', 'Longue cuillère avec un manche torsadé, souvent avec un petit disque ou une fourchette à l''extrémité. Utilisée pour remuer les cocktails dans un verre à mélange et pour créer des couches dans les cocktails.
', 'Remuez doucement les ingrédients dans un mouvement circulaire pour éviter de casser la glace.', 'Si vous n''avez pas de cuillère de bar, vous pouvez tout à fait la remplacer par le manche d''une cuillère en bois ou tout autre ustensile de votre cuisine.', 'bar_spoon_1.webp', 'bar_spoon_2.webp', 'bar_spoon_3.webp'),
('Mixing glass', 'Verre à mélange large et épais utilisé pour mélanger les ingrédients des cocktails qui ne nécessitent pas d''être shaké. Utilisé avec une cuillère de bar pour mélanger les cocktails comme les Martini et les Manhattan.','Remplissez le verre de glace, ajoutez les ingrédients, remuez doucement avec une cuillère à mélange, puis versez dans le verre de service à l''aide d''une passoire. Attention lors du lavage : les verres à mélange sont souvent sensibles aux changements de température. Laissez-les revenir à température ambiante avant de les rincer.', 'Si vous ne disposez pas de verre à mélange, vous pouvez opter pour une pinte de bière ou un petit saladier.', 'mixing_glass_1.webp', 'mixing_glass_2.webp', 'mixing_glass_3.webp'),
('Strainer', 'Passoire utilisé pour filtrer les glaçons et autres solides en versant le cocktail dans le verre de service. Les trois types principaux sont la passoire Hawthorne (avec un ressort), la passoire Julep (en métal perforé) et la passoire fine (chinois). Utilisée pour filtrer les glaçons après avoir shaké ou mélangé un cocktail.', ' Placez la passoire sur le shaker ou le verre à mélange pour filtrer les ingrédients solides avant de verser le cocktail dans le verre de service.', 'Si vous n''avez pas de passoire, vous pouvez utiliser un couvercle de bocal préalablement perforé ou une cuillère à trous, comme une écumoire.', 'strainer_1.webp', 'strainer_2.webp', 'strainer_3.webp'),
('Pilon', 'Bâton en bois ou en métal utilisé pour écraser les fruits, les herbes et le sucre dans le fond d''un verre. Permet de libérer les arômes des ingrédients dans les cocktails comme le Mojito et la Caipirinha.', 'Placez les ingrédients dans le verre, puis pressez fermement mais doucement avec le pilon.', 'Si vous n''avez pas de pilon, vous pouvez utiliser le manche d''une cuillère en bois ou tout autre ustensile de cuisine robuste.', 'pilon_1.webp', 'pilon_2.webp', 'pilon_3.webp'),
('Doseur', 'Petit outil de mesure en forme de sablier utilisé pour doser les ingrédients liquides. Il a généralement deux côtés, un côté plus grand et un côté plus petit.', 'Utilisez le jigger pour mesurer précisément les ingrédients liquides, garantissant ainsi l''équilibre des saveurs dans vos cocktails.', 'Si vous n''avez pas de jigger, vous pouvez utiliser une petite tasse à mesurer, une cuillère à soupe, ou un verre doseur pour mesurer vos ingrédients.', 'doseur_1.webp', 'doseur_2.webp', 'doseur_3.webp'),
('Presse-agrumes', 'Le presse-agrumes est un outil essentiel pour tout amateur de cocktails désireux d''ajouter une touche de fraîcheur et d''intensité à ses boissons. Conçu pour extraire le jus des agrumes tels que les citrons, les citrons verts, les oranges et les pamplemousses, cet appareil vous permet de capturer toute la saveur et les nutriments des fruits sans effort.', 'Il est toujours préférable d''utiliser du jus frais, mais si vous manquez de temps, vous pouvez opter pour du jus en bouteille. Cependant, il est conseillé d''éviter les jus de type Pulco.', 'Ce n''est pas la méthode idéale, mais en l''absence de presse-agrumes, vous pouvez toujours presser le fruit à la main.', 'presse_agrumes_1.webp', 'presse_agrumes_2.webp', 'presse_agrumes_3.webp'),
('Verres à shot', 'Petits verres utilisés pour mesurer et servir les spiritueux purs ou les shooters.', 'Versez l''alcool, le cocktail, la liqueur ou l''eau-de-vie dans le verre, puis trinquez avec un "shot"!', 'Si vous n''avez pas de verre à shot, vous pouvez utiliser de petites tasses à expresso ou à thé comme alternative.', 'verres_a_shot_1.webp', 'verres_a_shot_2.webp', 'verres_a_shot_3.webp'),
('Blender', 'Mixeur électrique utilisé pour mélanger des ingrédients à haute vitesse. Idéal pour les cocktails glacés et les smoothies.','Placez les ingrédients dans le bol du blender, fixez le couvercle, et sélectionnez la vitesse ou le mode approprié. En quelques secondes, vous obtiendrez une texture homogène et lisse, parfaite pour vos recettes de cocktails.', 'Si vous n''avez pas de blender, vous pouvez utiliser un mixeur plongeant ou les fonctions de certains robots culinaires.', 'blender_1.webp', 'blender_2.webp', 'blender_3.webp'),
('Zesteur', 'Petit outil utilisé pour prélever des zestes d''agrumes pour les utilisés comme garniture ou décoration.', 'Il suffit de frotter le zesteur contre l''écorce des agrumes en exerçant une pression légère, en veillant à éviter la partie blanche amère sous l''écorce.', 'En l''absence de zesteur ou d''économe, vous pouvez découper le zeste avec un petit couteau en suivant la forme du fruit.', 'zesteur_1.webp', 'zesteur_2.webp', 'zesteur_3.webp'),
('Pourer', 'Bec verseur fixé sur la bouteille pour verser facilement et avec précision les spiritueux. Utilisé pour contrôler le débit des liquides lors du versement, ce qui permet des mesures plus précises et une présentation plus professionnelle.', 'Pour l''utiliser, il suffit d''enficher le pourer dans le goulot de la bouteille et de verser le liquide en inclinant légèrement la bouteille, ce qui permet de verser avec précision et d''éviter les éclaboussures.', 'Si vous n''avez pas de bec verseur mais souhaitez obtenir des doses précises, le mieux est d''utiliser un doseur.', 'pourer_1.webp', 'pourer_2.webp', 'pourer_3.webp'),
('Limonadier', 'Outil multifonctionnel comprenant un tire-bouchon, une lame pour couper et un décapsuleur. Utilisé pour ouvrir les bouteilles de vin, de bière et les sodas.', 'Pour l''utiliser, placez le limonadier sous le bord de la capsule ou du bouchon, puis exercez une pression pour le soulever et le retirer de la bouteille.', 'Il est possible d''utiliser le manche d''une cuillère pour faire levier et décapsuler une bouteille, mais soyez prudent pour éviter de vous blesser ou de casser la bouteille. Cette méthode est déconseillée en raison des risques associés.', 'limonadier_1.webp', 'limonadier_2.webp', 'limonadier_3.webp'),
('Entonnoir', 'Petit outil en forme de cône utilisé pour transférer des liquides d''un récipient à un autre sans renverser.', 'Placez l''entonnoir dans l''ouverture du récipient de destination, puis versez lentement le liquide dans l''entonnoir, qui le dirigera proprement dans le récipient sans déversement.', 'Si vous n''avez pas d''entonnoir, vous pouvez utiliser un bec verseur si le produit n''est pas trop épais, ou fabriquer un entonnoir temporaire en utilisant du papier cuisson.', 'entonnoir_1.webp', 'entonnoir_2.webp', 'entonnoir_3.webp'),
('Glace', 'Il existe trois principaux types de glace : les glaçons classiques, utilisés pour les cocktails "on the rocks" ou dans le shaker ; la glace pilée, qui fond plus rapidement et dilue davantage les cocktails, idéale pour des boissons comme le mojito ou la caipirinha ; et enfin, les gros glaçons sphériques ou cubiques, utilisés pour des cocktails haut de gamme, offrant une dilution beaucoup plus lente.', 'La qualité et la forme de la glace peuvent affecter la dilution et la présentation de votre cocktail. La glace sèche et la glace humide ont des taux de dilution différents, ce qui peut nécessiter un ajustement des recettes en fonction du type de glace utilisé. ', 'Si vous n''avez pas de glace pilée, vous pouvez placer des glaçons dans un torchon et les écraser avec un rouleau à pâtisserie ou un marteau. Pour distinguer la glace sèche de la glace humide, il suffit de la prendre en main. Si elle colle à vos doigts, il s''agit de glace sèche. La glace sèche se dilue beaucoup moins que la glace humide.', 'glace_1.webp', 'glace_2.webp', 'glace_3.webp');


INSERT INTO "ingredient" ("name", "description", "url_image") VALUES ('Vodka', 'Spiritueux neutre et pur, distillé à partir de céréales ou de pommes de terre.', 'vodka.webp'),
('Gin', 'Spiritueux distillé à partir de céréales ou d''orge, aromatisé principalement avec des baies de genièvre et des herbes.', 'gin.webp'),
('Rhum', 'Spiritueux distillé à partir de canne à sucre ou de mélasse.', 'rhum.webp'),
('Spiced Rhum', 'Spiritueux distillé à partir de canne à sucre ou de mélasse et ajout d''épices', 'spiced_rhum.webp'),
('Tequila', 'Spiritueux distillé à partir de l''agave bleu, produit principalement au Mexique.', 'tequila.webp'),
('Mezcal', 'Spiritueux similaire à la tequila, mais produit à partir de divers types d''agave et souvent avec un goût fumé.', 'mezcal.webp'),
('Whisky', 'Spiritueux vieilli en fût, fabriqué à partir de grains tels que le maïs, le seigle, l''orge, ou le blé.', 'whisky.webp'),
('Whiskey', 'Spiritueux vieilli en fût, fabriqué à partir de grains tels que le maïs, le seigle, l''orge, ou le blé. D''origine américaine ou irlandaise.', 'whiskey.webp'),
('Bourbon', 'Spiritueux vieilli en fût, fabriqué majoritairement à partir de grains de maïs. D''origine américaine.', 'bourbon.webp'),
('Rye whiskey', 'Spiritueux vieilli en fût, fabriqué majoritairement à partir de grains de seigle. D''origine américaine.', 'rye_whiskey.webp'),
('Brandy', 'Spiritueux distillé à partir de vin ou d''autres fruits fermentés.', 'brandy.webp'),
('Triple sec', 'Liqueur d''orange utilisée par exemple dans les Margaritas et les Cosmopolitans. La plus connue est le Cointreau', 'triple_sec.webp'),
('Amaretto', 'Liqueur d''amande, souvent utilisée dans les cocktails comme l''Amaretto Sour.', 'amaretto.webp'),
('Limoncello', 'Liqueur de citron d''origine italienne', 'limoncello.webp'),
('Liqueur de café', 'Liqueur à base de café. La plus connue est le Kahlúa d''origine mexicaine.', 'liqueur_de_cafe.webp'),
('Sirop de sucre', 'Mélange de sucre et d''eau en proportions égales, utilisé pour sucrer les cocktails.', 'sirop_de_sucre.webp'),
('Sirop d''orgeat', 'Sirop au goût d''amandes', 'sirop_d_orgeat.webp'),
('Crème', 'Crème liquide', 'creme_liquide.webp'),
('Amer italien aperitivo', 'Aperol est un amer léger, orange, avec des notes d''agrumes, de rhubarbe et d''herbes. Il est moins amer que le Campari et possède une saveur plus douce.', 'amer_italien_aperitivo.webp'),
('Angostura', 'Bitters aromatiques utilisés pour ajouter de la profondeur et de la complexité aux cocktails.', 'angostura.webp'),
('Amer italien', 'Campari est un amer rouge vif, avec des saveurs d''agrumes, d''herbes et de fruits. Il est connu pour sa couleur distinctive et son goût amer prononcé.', 'amer_italien.webp'),
('Liqueur de framboise', 'Liqueur à base de framboise', 'liqueur_de_framboise.webp'),
('Liqueur de fleurs de sureau', 'Liqueur à base de fleurs de sureau. La plus connue étant le Saint Germain.', 'liqueur_de_fleurs_de_sureau.webp'),
('Jus d''ananas', 'Jus d''ananas.', 'jus_d_ananas.webp'),
('Jus de cranberry', 'Jus de cranberry.', 'jus_de_cranberry.webp'),
('Compote de poire', 'Compote de poire.', 'compote_poire.webp'),
('Jus de citron', 'Jus extrait du citron, utilisé pour ajouter une acidité et un éclat de saveur.', 'jus_de_citron.webp'),
('Jus de passion', 'Jus de fruits de la passion.', 'Jus_de_fruits_de_la_passion.webp'),
('Jus de citron vert', 'Jus extrait du lime, souvent utilisé pour son acidité vive et son goût légèrement amer.', 'jus_de_citron_vert.webp'),
('Citron vert', 'Citron vert', 'citron_vert.webp'),
('Menthe', 'Feuille de menthe', 'feuille_de_menthe.webp'),
('Ginger beer', 'Soda sans alcool pétillant au goût de gingembre prononcé.', 'ginger_beer.webp'),
('Lait de coco', 'Liquide crémeux extrait de la chair de noix de coco.', 'lait_de_coco.webp'),
('Blanc d''oeuf', 'Blanc d''oeuf.', 'blanc_d_oeuf.webp'),
('Aquafaba', 'Jus de cuisson ou liquide de conservation des pois chiche.', 'aquafaba.webp'),
('Expresso', 'Café court.', 'expresso.webp'),
('Prosecco dry', 'Vin effervescent italien', 'prosecco_dry.webp'),
('Pisco', 'Spiritueux à base de raisin au goût floral. Provient du Pérou et du Chili.', 'pisco.webp'),
('Eau gazeuse', 'Eau pétillante également appelée soda.', 'eau_petillante.webp'),
('Vermouth rouge', 'Vin fortifié aromatisé avec des herbes et des épices, souvent doux.', 'vermouth_rouge.webp'),
('Vermouth blanc', 'Vin fortifié aromatisé avec des herbes et des épices, souvent doux.', 'vermouth_blanc.webp'),
('Vermouth dry', 'Vin fortifié aromatisé avec des herbes et des épices, souvent sec.', 'vermouth_dry.webp'),
('orange', 'orange.', 'orange.webp'),
('Tonic', 'Boisson gazeuse contenant de la quinine ce qui donne un goût lègèrement amer.', 'tonic.webp'),
('Ananas frais', 'Ananas frais.', 'tranche_ananas_frais.webp'),
('Basilic', 'Feuille de basilic.', 'feuille_de_basilic.webp'),
('Thé baby boom', 'Infusion fenouil, anis et badiane', 'the_baby_boom.webp'),
('Vodka au safran', 'Vodka infusée au safran', 'vodka_safran.webp'),
('Sirop de cannelle', 'sirop à la cannelle', 'sirop_cannelle.webp'),
('Pêche fraiche', 'pêche fraiche', 'peche.webp'),
('Jus de pêche', 'Jus de pêche', 'jus_peche.webp'),
('Jus Aloe Vera', 'Jus d''aloe vera', 'jus-aloe-vera.webp'),
('Sirop de rose', 'sirop de rose', 'sirop_de_rose.webp'),
('Kiwi frais', 'kiwi frais', 'kiwi.webp'),
('Fruit de la passion', 'fruit de la passion', 'fruit_passion.webp'),
('Vodka vanille', 'Vodka vanille', 'vodka_vanille.webp'),
('Cachaça', 'Spiritueux brésilien à base de canne à sucre.', 'cachaca.webp'),
('Cordial verveine thym', 'Cordial verveine thym', 'cordial_verveine_thym.webp'),
('Lemon Bitters', 'Bitters citron', 'lemon_bitters.webp'),
('Lemon tonic', 'Tonic au citron', 'lemon_tonic.webp'),
('Thé vert mangue', 'Thé vert à la mangue', 'the_vert_mangue.webp'),
('Sirop spicy', 'Sirop spicy monin', 'sirop_spicy.webp');

INSERT INTO "recipe" ("name", "description", "advice", "history", "url_image", "step_1", "step_2", "step_3", "step_4", "step_5", "step_6", "method_id", "taste_id", "glass_id") VALUES ('Margarita', 'La Margarita est un cocktail composé de tequila, de liqueur d''orange et de jus de citron vert, souvent servi avec du sel sur le bord du verre. La boisson est servie shaké, avec de la glace (on the rocks), mélangée avec de la glace (margarita frozen) ou sans glace (straight up).', 'Salez le bord du verre pour une Margarita traditionnelle. D''abord, il faut mouiller le bord du verre avec un morceau de citron vert, puis passer le verre dans du sel. Pour un goût plus délicat, privilégiez une tequila reposado ou añejo.', 'La Margarita a été inventée en octobre 1941, au Hussong''s Cantina à Ensenada, au Mexique, par le barman Don Carlos Orozco.', 'margarita_cocktail.webp', 'Mouiller le Bord: Utilisez un quartier de citron vert pour mouiller le bord du verre à Margarita.', 'Givrer le Bord: Passez le bord du verre dans du sel pour le givrer. Réservez le verre.', 'Dans un shaker, combinez les ingrédients suivants : 50 ml de tequila, 25 ml de liqueur d''orange (comme le Triple Sec ou le Cointreau), 25 ml de jus de citron vert fraîchement pressé et Remplissez le shaker avec des glaçons.', 'Secouez vigoureusement le shaker pendant environ 15 secondes pour bien mélanger et refroidir la boisson.', 'Filtrer: Versez le mélange à travers une passoire dans le verre préparé.','Déguster', 1, 3, 4),
('Italian spritz', 'Il se compose principalement de trois ingrédients : Prosecco, Aperol (ou parfois Campari) et une touche d''eau gazeuse. Ce mélange crée une boisson pétillante, légèrement amère et rafraîchissante, souvent servie avec une tranche d''orange. Traditionnellement, le Spritz est apprécié comme apéritif lors des après-midis ensoleillés ou lors des apéritifs en soirée, offrant une explosion de saveurs vives et une couleur vibrante qui reflète l''esprit convivial de la culture italienne.', '
Il est possible de remplacer l''Aperol par d''autres liqueurs : le Saint Germain pour une explosion de fraîcheur et un goût floral, le Campari pour une amertume encore plus prononcée, le Limoncello pour une note citronnée, ou la liqueur de framboise pour un goût très fruité. La seule limite est votre imagination!', 'Le Spritz est un cocktail italien emblématique, originaire de la région de Venise. Le Spritz aurait été créé au 19e siècle lorsque les soldats autrichiens, alors en occupation en Italie du Nord, ont commencé à mélanger le vin local avec de l''eau gazeuse pour le rendre moins fort et plus rafraîchissant. Au fil des années, la recette du Spritz a évolué. Au lieu du simple mélange de vin et d''eau gazeuse, des liqueurs comme l''Aperol, le Campari, et le Select ont été ajoutées, donnant au cocktail ses saveurs distinctives et sa couleur vive.', 'italian_spritz_cocktail.webp', 'Remplir le verre avec de gros glaçons.', 'Verser l''Aperol, le Prosecco (de préférence extra dry pour ne pas ajouter trop de sucre) et l''eau gazeuse.', 'Remuer doucement pour mélanger les ingrédients.', 'Ajouter une rondelle d''orange', 'Rajouter de la glace si nécessaire', 'Déguster', 2, 4, 5),
('Piña Colada', 'La Piña Colada est un cocktail tropical crémeux à base de rhum, de jus d''ananas et de lait de coco. La boisson est généralement garnie d''une tranche d''ananas et d''une cerise au marasquin. La Piña Colada est un cocktail sucré et rafraîchissant, parfait pour les journées chaudes et ensoleillées.', 'Pour une version sans alcool, remplacez le rhum par du jus d''ananas supplémentaire et ajoutez un peu de sirop de Rhum pour la saveur.', 'La Piña Colada a été inventée en 1954 à Porto Rico par le barman Ramón "Monchito" Marrero. Il a créé la recette originale au Caribe Hilton Hotel à San Juan, en utilisant du rhum local, du jus d''ananas frais et du lait de coco.', 'pina_colada_cocktail.webp', 'Dans un blender, ajouter l''ananas frais.', 'Ajouter le rum, le jus d''ananas et le lait de coco.','Ajouter de la glace pilée à hauteur et mixer jusqu''à obtenir une texture lisse et crémeuse.', 'Verser le mélange dans un verre de type Hurricane ou Tiki', 'Garnir d''une tranche d''ananas et d''une cerise au marasquin.', 'Déguster', 4, 6, 12),
('Expresso martini', 'L''Expresso Martini est un cocktail énergisant et sophistiqué, mélangeant la saveur riche du café expresso avec la douceur de la liqueur de café et la force de la vodka. La boisson est servie dans un verre à Martini et est souvent garnie de grains de café pour une touche décorative. Les trois grains de café utilisés pour décorer un Espresso Martini représentent traditionnellement la santé, la richesse et le bonheur. Cette décoration symbolique est empruntée à une ancienne tradition italienne de servir Sambuca avec trois grains de café, appelée "con la mosca" (avec les mouches), qui se dit apporter ces trois souhaits au buveur.', 'Pour plus de douceur, il est possible de remplacer le sirop de sucre par du sirop de vanille ou de cerise selon vos goûts. Afin de garantir l''excellence, optez pour une vodka et un café de qualité supérieure. Il est également possible d''utiliser une liqueur de café aromatisée telle que la Patron Incendio, qui ajoutera un côté épicé et légèrement piquant. ', 'L''Espresso Martini a été inventé par Dick Bradsell, un célèbre barman britannique souvent surnommé le "parrain de la scène cocktail londonienne". La création a eu lieu au Fred''s Bar à Soho, Londres, où Bradsell travaillait à l''époque, en 1983. Selon la légende, une jeune femme (souvent identifiée comme un mannequin célèbre) est entrée dans le bar et a demandé un cocktail qui "me réveillera, puis me cassera" (en anglais : "wake me up, then fuck me up").', 'expresso_martini_cocktail.webp', 'Mettre des glaçons dans le verre pour le rafraîchir (il est également possible de garder ses verres au réfrigérateur quelques minutes avant).', 'Dans le shaker, ajouter tous les ingrédients en terminant par le café.', 'Ajouter de la glace dans le shaker et shaker énergiquement.', 'Enlever les glaçons du verre et passer le cocktail dans le verre en utilisant une passoire supplémentaire pour récupérer les petits morceaux de glace qui se sont cassés dans le shaker.', 'Décorer avec 3 petits grains de café.', 'Déguster.',1,1,1),
('Dark & Stormy', 'Le Dark and Stormy est un cocktail rafraîchissant qui marie la chaleur du rhum avec le piquant du gingembre. Ce mélange audacieux est composé de rhum noir, du soda au gingembre (ginger beer) et d’un trait de jus de citron vert, le tout servi sur glace. Le rhum noir, avec ses notes riches et profondes, contraste parfaitement avec la légèreté épicée du sosa au gingembre, tandis que le citron vert ajoute une touche d''acidité vivifiante. Ce cocktail se distingue par sa couleur sombre, provenant du rhum, qui se dégrade en un dégradé doré avec la bière au gingembre, évoquant une tempête tumultueuse en mer.', 'Aux États-Unis, la marque Gosling''s a déposé le nom "Dark n'' Stormy", ce qui signifie que le cocktail ne peut être vendu sous ce nom là-bas que lorsqu''il est préparé avec le rhum Gosling''s Black Seal. Ainsi, toute variante utilisant un autre rhum doit être appelée autrement.', 'Le Dark and Stormy trouve ses origines dans les Bermudes, où il est né au début du XXe siècle. Ce cocktail est devenu emblématique grâce à la marque de rhum noir Gosling''s, qui revendique la paternité de la recette. Selon la légende, le cocktail a été créé par des marins britanniques qui, en mélangeant du rhum noir avec de la bière au gingembre, ont vu une similitude entre la boisson et les tempêtes violentes qu''ils affrontaient en mer, d''où le nom évocateur. Au fil des années, le Dark and Stormy a gagné en popularité au-delà des Bermudes et est devenu un classique apprécié dans le monde entier pour son goût rafraîchissant et sa facilité de préparation.', 'dark_and_stormy_cocktail.webp', 'Remplir le verre de glace.', 'Presser le jus de citron vert au dessus du verre et verser le ginger beer.', 'Ajouter de la glace si nécessaire.', 'En top, à l''aide de la bar spoon, verser le rhum au-dessus afin qu''il reste en surface.', 'Mélanger légèrement pour créer l''effet "stormy".', 'Déguster.', 6, 5, 3),
('Gin basil smash', 'Le Gin Basil Smash est un cocktail rafraîchissant et aromatique qui marie la fraîcheur du basilic avec la complexité du gin. Ce mélange équilibré est composé de gin, de jus de citron frais, de sirop de sucre et de feuilles de basilic, créant une boisson vibrante et herbacée. Le Gin Basil Smash est souvent servi dans un verre old fashioned sur glace, garni de feuilles de basilic pour une touche de fraîcheur et de couleur.', 'Pour une version plus épicée, ajoutez quelques grains de poivre noir ou de piment. Il est également possible d''utiliser différents types de basilic : le basilic thaï pour un cocktail plus épicé, le basilic citronné pour une fraîcheur accrue, ou encore le basilic rouge pour une magnifique couleur pourpre.', 'Le Gin Basil Smash a été inventé par le barman allemand Jörg Meyer en 2008, au Le Lion Bar de Hambourg. Meyer a créé le cocktail en utilisant des ingrédients simples et de qualité pour mettre en valeur la saveur du gin et du basilic. Depuis sa création, le Gin Basil Smash est devenu un cocktail emblématique de la scène cocktail internationale, apprécié pour sa fraîcheur et sa simplicité.', 'gin_basil_smash_cocktail.webp', 'Remplir le verre de glace pour le rafraîchir.', 'Mettre le basilic dans le shaker et piler énergiquement pour extraire tout son arôme.', 'Ajouter les autres ingrédients.', 'Ajouter de la glace et shaker de façon énergique.', 'Filtrer le mélange dans le verre à l''aide d''une passoire.', 'Ajouter une feuille de basilic sur le dessus du verre et déguster.',  1, 7, 2),
('Bourbon old fashioned', 'Le Old Fashioned est un cocktail classique et intemporel qui met en valeur la richesse et la complexité du bourbon. Ce mélange simple et élégant est composé de bourbon, de sucre, d''Angostura bitters et d''un zeste d''orange, créant une boisson riche et équilibrée. Le Old Fashioned est souvent servi dans un verre old fashioned sur glace, garni d''un zeste d''orange pour une touche d''acidité et de fraîcheur.', 'Pour une version plus sucrée, ajoutez un peu de sirop de sucre supplémentaire. Il est également possible de remplacer le bourbon par du whisky, du rye whiskey ou du brandy pour une variante différente. Il est également possible de remplacer le classique Angostura bitters par un bitters au café, à la cerise, au chocolat, ou même pimenté, selon vos préférences.  Si vous ne réalisez qu''un cocktail, vous pouvez le préparer directement dans le verre de service en ajoutant les glaçons au fur et à mesure afin de diluer le cocktail.', 'Le Old Fashioned est l''un des cocktails les plus anciens et les plus célèbres de l''histoire, remontant au début du XIXe siècle. Il est considéré comme le premier cocktail "moderne" et a été créé à l''origine avec du sucre, de l''eau-de-vie, de l''eau et des bitters. La recette a évolué pour inclure du bourbon ou d''autres spiritueux, mais l''esprit du Old Fashioned reste le même : un cocktail simple, élégant et délicieux.', 'old_fashioned_cocktail.webp', 'Remplir de glace le verre à mélange et le verre de dégustation.', 'Ajouter les ingrédients dans le verre à mélange.', 'Mélanger pendant environ deux minutes pour diluer le cocktail.', 'Passer le cocktail dans le verre de dégustation.', 'Zester un zeste d''orange et l’exprimer (appuyer dessus pour extraire les huiles essentielles).', 'Déguster.', 2, 12, 2),
('Negroni', 'Le Negroni est un cocktail italien classique et sophistiqué qui marie l''amertume du Campari avec la douceur du vermouth rouge et la force du gin. Ce mélange équilibré est composé de gin, de vermouth rouge et de Campari, créant une boisson complexe et riche en saveurs. Le Negroni est souvent servi dans un verre old fashioned sur glace, garni d''une tranche d''orange pour une touche de fraîcheur et de couleur.', 'Pour une version plus douce, remplacez le Campari par de l''Aperol. Pour une version plus amère, remplacez le Campari par du Fernet Branca. Il est également possible de remplacer le gin par du bourbon pour faire un Boulevardier', 'Le Negroni a été inventé en 1919 à Florence, en Italie, par le comte Camillo Negroni. L''histoire raconte que le comte, un habitué du Caffè Casoni, a demandé au barman de renforcer son cocktail Americano en remplaçant l''eau gazeuse par du gin. Le barman a ajouté une tranche d''orange pour décorer le verre, et le Negroni est né. Depuis lors, le Negroni est devenu un cocktail emblématique de la scène cocktail internationale, apprécié pour son équilibre et sa complexité.', 'negroni_cocktail.webp', 'Remplir le verre de glace pour le rafraîchir.', 'Verser le gin, le vermouth rouge et le Campari dans le verre.', 'Remuer doucement pour mélanger les ingrédients.', 'Ajouter une tranche d''orange.', 'Ajouter de la glace si nécessaire.', 'Déguster.', 6, 4, 2),
('Amaretto sour', 'L''Amaretto Sour est un cocktail sucré et acidulé qui marie la douceur de l''amaretto avec l''acidité du citron. Ce mélange équilibré est composé d''amaretto, de jus de citron frais, de sirop de sucre et de blanc d''œuf, créant une boisson crémeuse et rafraîchissante. L''Amaretto Sour est souvent servi dans un verre old fashioned sur glace, garni d''une cerise au marasquin pour une touche de couleur et de douceur.', 'Pour une version plus douce, ajoutez un peu de sirop de sucre supplémentaire. Pour une version plus acidulée, ajoutez un peu plus de jus de citron. Il est également possible de remplacer le blanc d''œuf par de l''aquafaba pour une version végétalienne. Les "sours" sont une grande famille de cocktails. Il est possible de remplacer l''amaretto par du whisky, du pisco, du bourbon, etc.', 'L''Amaretto Sour est un cocktail classique qui a été créé dans les années 1970. Il est devenu populaire dans les bars et les discothèques de l''époque pour son goût sucré et acidulé, qui était apprécié par les amateurs de cocktails. Depuis lors, l''Amaretto Sour est devenu un cocktail emblématique de la scène cocktail internationale, apprécié pour sa simplicité et sa délicieuse combinaison de saveurs.', 'amaretto_sour_cocktail.webp', 'Remplir le verre de glace pour le rafraîchir.', 'Verser les ingédients dans le shaker.', 'Shaker vigoureusement sans glace pour bien mélanger et émulsionner les ingrédients.','Saker une seconde fois avec de la glace', 'Filtrer le mélange dans le verre.', 'Déguster.', 1, 1, 2),
('Aqua vitae', 'Ce cocktail sophistiqué allie des saveurs exotiques et épicées pour offrir une expérience gustative unique. Confectionné avec une vodka infusé au safran, il se distingue par son arôme délicat et sa belle couleur dorée. L''amertume subtile de l''Angostura se marie parfaitement avec la douceur du sirop de cannelle, tandis que l''aquafaba apporte une texture soyeuse et un aspect mousseux attrayant. Le jus de citron ajoute une touche de fraîcheur et d''acidité qui équilibre les saveurs. Le thé Baby Boom, une infusion d''anis, fenouil et badiane, complète le mélange avec des notes légèrement réglissées et herbacées, apportant une complexité supplémentaire au cocktail.', 'Pour obtenir la vodka au safran, il faut infuser 1 gramme de pistilles de safran dans 70 cl de vodka pendant 48 heures. Il est impératif de choisir une vodka de qualité, comme la vodka française Grey Goose, la vodka polonaise Belvedere ou la vodka russe Beluga. Pour l''infusion baby boom, il faut la faire infuser et attendre qu''elle refroidisse avant de l''utiliser.', 'Ce cocktail a été conçu pour capturer et recréer les arômes distincts de l''eau-de-vie scandinave "aquavit", qui reste assez méconnue chez nous. En mélangeant des ingrédients soigneusement sélectionnés, ce cocktail offre une alliance harmonieuse de saveurs subtiles et de fraîcheur. L''objectif était de rendre hommage aux caractéristiques uniques de l''aquavit tout en proposant une boisson rafraîchissante et accessible, capable de séduire les palais les plus exigeants.', 'aqua_vitae_cocktail.webp', 'Remplir le verre de glace pour le rafraîchir.', 'Verser les ingrédients dans le shaker.', 'Shaker vigoureusement sans glace pour bien mélanger et émulsionner les ingrédients.','Saker une seconde fois avec de la glace', 'Filtrer le mélange dans le verre.', 'Déguster.', 1, 5, 2),
('Mojito', 'Le Mojito est un cocktail rafraîchissant et pétillant qui marie la fraîcheur de la menthe avec l''acidité du citron vert et la douceur du sucre. Ce mélange équilibré est composé de rhum, de menthe fraîche, de sucre, de citron vert et d''eau gazeuse, créant une boisson vivifiante et herbacée. Le Mojito est souvent servi dans un verre highball sur glace pilée, garni de feuilles de menthe pour une touche de fraîcheur et de couleur.', 'Pour une version plus sucrée, ajoutez un peu de sirop de sucre supplémentaire. Pour une version plus acidulée, ajoutez un peu plus de jus de citron vert. Il est également possible de remplacer le sirop de sucre par du sucre en grains pour plus de gourmandise. Si vous aimez l''amertume vous pouvez ajouter deux traits d''Angostura bitters. Il est préférable de choisir un rhum cubain pour respecter la recette d''origine.', 'Le Mojito est un cocktail cubain classique qui a été créé au 16e siècle. Il est devenu populaire dans les bars et les restaurants de La Havane pour son goût rafraîchissant et sa simplicité. Depuis lors, le Mojito est devenu un cocktail emblématique de la scène cocktail internationale, apprécié pour sa fraîcheur et sa vivacité.', 'mojito_cocktail.webp', 'Mettre les feuilles de menthe dans le verre et les piler sans les broyer pour garder la menthe entière et libérer les arômes.', 'Remplir la moitié du verre avec de la glace pilée.', 'Ajouter le rhum, le jus de citron vert, le sirop de sucre et mélanger de bas en haut.', 'Remplir le verre de glace pilée et compléter d''eau gazeuse.', 'Mélanger une dernière fois.', 'Déguster.', 3, 3, 3),
('Daiquiri pêche frozen', 'Le Daiquiri est un cocktail classique et rafraîchissant qui marie la douceur de la pêche avec l''acidité du citron vert et la force du rhum. Ce mélange équilibré est composé de rhum, de pêche fraiche, de jus de citron vert et de glace pilée, créant une boisson crémeuse et rafraîchissante. Le Daiquiri est souvent servi dans un verre à cocktail garni d''une tranche de pêche pour une touche de fraîcheur et de couleur.', 'Pour une version plus sucrée, ajoutez un peu de sirop de sucre supplémentaire. Pour une version plus acidulée, ajoutez un peu plus de jus de citron vert. Il est également possible de remplacer la pêche par vos fruits préférés', 'Le Daiquiri est un cocktail cubain classique qui a été créé au 19e siècle. Il est devenu populaire dans les bars et les restaurants de La Havane pour son goût rafraîchissant et sa simplicité. Depuis lors, le Daiquiri est devenu un cocktail emblématique de la scène cocktail internationale, apprécié pour sa fraîcheur et sa vivacité.', 'daiquiri_peche_frozen_cocktail.webp', 'Éplucher et découper la pêche en morceaux.', 'Mettre tous les ingrédients dans le blender.', 'Ajouter de la glace pilée jusqu''à hauteur.', 'Mixer pour obtenir une texture lisse et homogène.','Verser dans le verre.', 'Déguster.', 4, 6, 1),
('Spritz hugo', 'Il se compose principalement de trois ingrédients : Prosecco, liqueur de fleurs de sureau (par exemple Saint Germain) et une touche d''eau gazeuse. Ce mélange crée une boisson pétillante, légèrement florale et rafraîchissante, souvent servie avec une tranche de citron vert et de la menthe. Traditionnellement, le Spritz est apprécié comme apéritif lors des après-midis ensoleillés ou lors des apéritifs en soirée, offrant une explosion de saveurs vives et une couleur vibrante qui reflète l''esprit convivial de la culture italienne.', '
Il est possible de remplacer la liqueur de fleurs de sureau par d''autres liqueurs : l''aperol pour une légère amertume, le Campari pour une amertume encore plus prononcée, le Limoncello pour une note citronnée, ou la liqueur de framboise pour un goût très fruité. La seule limite est votre imagination!', 'Le Spritz Hugo a été créé par l''hôtelière et restauratrice tirolienne, Roland Gruber, dans la région de Trentin-Haut-Adige, en Italie du Nord, vers la fin des années 2000. Ce cocktail a été conçu pour offrir une alternative rafraîchissante au Spritz classique, en mettant en avant des saveurs plus florales et herbacées. Le nom "Hugo" a été choisi en l''honneur d''un ami du créateur, et le cocktail a rapidement gagné en popularité grâce à son goût rafraîchissant et sa présentation attrayante. Il est souvent servi dans un grand verre à vin ou un verre à cocktail avec beaucoup de glace, et décoré de feuilles de menthe et de tranches de lime. Le succès du Spritz Hugo a contribué à la popularisation des cocktails à base de fleurs de sureau dans le monde entier, et il est devenu un choix populaire lors des apéritifs et des événements estivaux.', 'spritz_hugo_cocktail.webp', 'Remplir le verre avec de gros glaçons.', 'Verser la liqueur, le Prosecco (de préférence extra dry pour ne pas ajouter trop de sucre) et l''eau gazeuse.', 'Remuer doucement pour mélanger les ingrédients.', 'Ajouter les quartiers de citron vert et la menthe', 'Rajouter de la glace si nécessaire', 'Déguster', 2, 8, 5),
('Tiki pear', 'Les cocktails tiki sont des boissons tropicales souvent élaborées avec plusieurs types de rhum, des jus de fruits, des sirops et des bitters, et servis dans des verres ou mugs décoratifs. Les cocktails tiki sont connus pour leurs saveurs complexes et exotiques, leurs couleurs vives et leurs décorations extravagantes. Ils sont souvent garnis de fruits frais, de parasols, de pailles colorées et de décorations en forme de palmiers ou de fleurs. Les cocktails tiki sont parfaits pour les fêtes estivales, les barbecues en plein air et les soirées à thème hawaïen.', 'Pour une version plus épicée, ajoutez des épices comme la cannelle, le gingembre ou le piment. Il est également possible de remplacer le rhum par de la tequila, de la vodka ou du gin pour des variantes intéressantes.', 'Les cocktails tiki ont été créés dans les années 1930 par le barman américain Donn Beach, également connu sous le nom de Don the Beachcomber. Beach a ouvert le premier bar tiki à Hollywood, en Californie, où il a inventé des recettes de cocktails exotiques inspirées des saveurs des îles du Pacifique. Les cocktails tiki sont devenus populaires dans les années 1940 et 1950, grâce à leur mélange de saveurs tropicales, de rhum et de décoration thématique. Depuis lors, les cocktails tiki sont devenus un classique de la scène cocktail internationale, appréciés pour leur exotisme et leur originalité.', 'tiki_cocktail.webp', 'Remplir le verre de glace pour le rafraîchir.', 'Verser les ingrédients dans le shaker.', 'Shaker vigoureusement avec de la glace.', 'Filtrer le mélange dans le verre.', 'Décorer avec des fruits frais, des parasols et des pailles colorées.', 'Déguster.', 1, 6, 12),
('Kiwix', 'Le Kiwix est un cocktail rafraîchissant et fruité qui marie la douceur du kiwi avec l''acidité du citron vert et la force du gin. Ce mélange équilibré est composé de gin, de kiwi frais, de jus de citron vert, de sirop de rose et de jus d''aloe vera,' , 'Il est crucial de mixer le cocktail au blender avant de le shaker pour réduire les grains de kiwi, ce qui libérera une délicate note poivrée et ajoutera de la profondeur au goût du mélange. Il est également important d''utiliser du gin Hendrick’s, qui se distingue par son élaboration à base de concombre et de rose, pour enrichir encore davantage le profil aromatique du cocktail.', 'Le Kiwix a été inventé en 2010 par le talentueux barman français Kévin Standaert, alors qu''il travaillait au bar du Wiltcher''s, un prestigieux hôtel de luxe situé à Bruxelles. Cette création a été spécialement élaborée pour marquer la finale du concours Hendrick’s Chimera.', 'kiwix_cocktail.webp', 'Éplucher et découper un kiwi entier.', 'Mettre le kiwi découpé et les autres ingrédients dans le blender.','Mixer jusqu''à obtenir une texture homogène.','Verser la préparation dans un shaker rempli de glace et shaker énergiquement.','Filtrer le mélange dans un verre rempli de glace.','Déguster.', 1, 6, 2),
('Porn star martini', 'Le Porn Star Martini se distingue par sa couleur dorée vive et est souvent décoré d''un demi-fruit de la passion en garniture. Sa combinaison de saveurs fruitées et sucrées en fait une option populaire pour ceux qui recherchent une boisson élégante et raffinée.', 'Il est possible de remplacer le shot de champagne par du prosecco ou un autre vin effervescent sec. Pour une touche plus gourmande, vous pouvez caraméliser le fruit de la passion avec un peu de sucre à l''aide d''un chalumeau.', 'Le Porn Star Martini est un cocktail moderne et audacieux, connu pour son goût tropical et sa présentation élégante. Créé au début des années 2000 par le barman britannique Douglas Ankrah, ce cocktail allie la douceur du fruit de la passion à la richesse de la vanille et la complexité du vodka. Le nom Porn Star Martini joue sur un jeu de mots et fait référence au geste de dégustation du fruit de la passion pour accentuer le caractère sensuel et élégant du cocktail, tout en éveillant l''intérêt des amateurs de cocktails.', 'porn_star_martini_cocktail.webp', 'Dans un shaker, vider la moitié d''un fruit de la passion et réserver l''autre moitié pour la dégustation.','Verser les autres ingrédients dans le shaker et shaker vigoureusement avec de la glace.','Filtrer le mélange dans un verre.','Déposer le demi-fruit de la passion sur le cocktail.','Servir avec un shot de champagne.','Boire le shot de champagne en premier pour "rincer les papilles", déguster le cocktail, puis terminer par le fruit de la passion.', 1, 6, 1),
('Caipirinha', 'La Caipirinha est un cocktail brésilien classique et rafraîchissant qui marie la douceur de la cachaça avec l''acidité du citron vert et la force du sucre. Ce mélange équilibré est composé de cachaça, de citron vert, de sucre et de glace pilée, créant une boisson vivifiante et acidulée. La Caipirinha est souvent servie dans un verre old fashioned sur glace pilée, garnie de quartiers de citron vert pour une touche de fraîcheur et de couleur.', 'Pour une version plus sucrée, ajoutez un peu de sirop de sucre supplémentaire. Pour une version plus acidulée, ajoutez un peu plus de jus de citron vert. Il est également possible d''ajouter d''autres fruits pour aromatiser le cocktail, comme la passion, la fraise ou la framboise.', 'La Caipirinha est un cocktail brésilien traditionnel qui a été créé au 19e siècle. Il est devenu populaire dans les bars et les restaurants de Rio de Janeiro pour son goût rafraîchissant et sa simplicité. Depuis lors, la Caipirinha est devenue un cocktail emblématique de la scène cocktail internationale, appréciée pour sa fraîcheur et sa vivacité', 'caipirinha_cocktail.webp', 'Couper le citron vert en quartiers.', 'Mettre les quartiers de citron vert et le sucre dans le verre.', 'Piler pour extraire le jus et les huiles essentielles du citron vert.', 'Remplir le verre de glace pilée.', 'Verser la cachaça sur la glace et mélanger doucement.', 'Ajouter de la glace si nécessaire et déguster', 3, 3, 2),
('Moscow Mule', 'Le Moscow Mule est un cocktail rafraîchissant et pétillant qui marie la chaleur de la vodka avec le piquant du gingembre et l''acidité du citron vert. Ce mélange équilibré est composé de vodka, de ginger beer et de jus de citron vert, créant une boisson vive et acidulée. Le Moscow Mule est souvent servi dans une tasse en cuivre sur glace pilée, garni d''une tranche de citron vert pour une touche de fraîcheur et de couleur.', 'Vous pouvez remplacer la vodka par du gin pour réaliser un London Mule, ou utiliser de la vodka aromatisée (comme au concombre, à la myrtille ou au piment) pour varier les saveurs. Optez pour une vodka de qualité et un ginger beer au goût intense (comme Fever-Tree) pour garantir un cocktail riche en saveurs.', 'Le Moscow Mule a été inventé dans les années 1940 par John G. Martin, un vendeur de vodka, et Jack Morgan, le propriétaire d''une entreprise de ginger beer, dans le but de promouvoir leurs produits respectifs. Le cocktail a été servi pour la première fois dans une tasse en cuivre, qui est devenue emblématique du Moscow Mule. Depuis lors, le Moscow Mule est devenu un cocktail classique apprécié pour sa simplicité et sa vivacité', 'moscow_mule_cocktail.webp', 'Remplir la tasse en cuivre de glace pour la rafraîchir.', 'Verser la vodka et le jus de citron vert dans la tasse.', 'Remplir la tasse de ginger beer.', 'Ajouter de le glace si nécessaire et mélanger doucement.', 'Ajouter une tranche de citron vert.', 'Déguster.', 6, 5, 9),
('Verbena', 'Le Verbena est un cocktail raffiné à base de tequila, combiné avec un cordial de verveine et de thym. Ce mariage d''herbes aromatiques, associé à la vivacité d''un tonic au citron, crée une boisson rafraîchissante et bien équilibrée. Idéal pour des apéritifs originaux, le Verbena est facile à déguster, offrant une expérience gustative unique et sophistiquée.', 'Pour créer le cordial, commencez par infuser 10 grammes de verveine séchée et 4 branches de thym séché dans 50 cl d''eau chauffée à environ 90 degrés Celsius. Maintenez l''infusion pendant environ 10 à 15 minutes pour permettre aux arômes et huiles essentielles des herbes de se libérer pleinement. Ensuite, ajoutez 10 cl de sirop de sucre au mélange infusé, en remuant bien pour que le sucre se dissolve complètement. Filtrez le liquide pour éliminer les résidus de plantes. Le résultat est un cordial parfumé et légèrement sucré, prêt à être utilisé comme base aromatique pour le cocktail Verbena, apportant une touche herbacée et rafraîchissante à chaque gorgée. Pour le tonic au citron, nous vous recommandons le Bitter Lemon de Fever-Tree.', 'Le cocktail Verbena a été conçu par le barman français Kévin Standaert, qui officiait au bar du Noao à Lille. Cette création unique fait partie d''une carte étendue de cocktails innovants, mettant en avant l''utilisation de thés et d''infusions. Le Verbena, en particulier, illustre parfaitement l''art de marier des ingrédients herbacés pour offrir une expérience gustative raffinée et rafraîchissante.', 'verbena_cocktail.webp', 'Remplir le verre de glace pour le rafraîchir.','Ajouter tous les ingrédients, en terminant par le tonic.','Mélanger légèrement pour homogénéiser la boisson.','Goûter le cocktail et ajuster l''acidité selon la douceur du cordial.','Ajouter de la glace si nécessaire.','Déguster.', 6, 7, 3),
('Tiki tea', 'Le Tiki Tea est un cocktail distinctif qui marie habilement du rhum épicé avec un thé à la mangue. Ce mélange innovant se distingue par sa capacité à offrir une richesse et une profondeur de saveurs incomparables. Le thé à la mangue, avec ses notes tropicales et légèrement sucrées, se marie parfaitement avec les épices du rhum, créant ainsi une complexité de goût que les autres boissons ne peuvent égaler. Le résultat est un cocktail aux saveurs exotiques et envoûtantes, qui évoque une escapade dans les tropiques tout en offrant une expérience gustative raffinée et inédite.', 'Il est crucial de respecter le temps d''infusion recommandé pour le thé afin de garantir une saveur optimale. Un dépassement de ce temps peut entraîner le développement de notes d''amertume et de brûlé, ce qui peut nuire à l''équilibre du goût du cocktail. Pour notre part, nous avons choisi le thé TEATAP Mangoustan, qui est un thé vert aromatisé à la mangue et aux fruits de la passion. Ce thé offre un goût délicatement fruité et équilibré, parfait pour compléter notre mélange tout en préservant des saveurs riches et agréables.', 'Le cocktail Tiki tea a été conçu par le barman français Kévin Standaert, qui officiait au bar du Noao à Lille. Cette création unique fait partie d''une carte étendue de cocktails innovants, mettant en avant l''utilisation de thés et d''infusions. Le Tiki tea, en particulier, illustre parfaitement l''art de marier des ingrédients originaux pour offrir une expérience gustative raffinée et rafraîchissante. Pour le sirop épicé, nous utilisons le sirop Monin Spicy.', 'tiki_tea_cocktail.webp', 'Refroidir le verre en le remplissant de glace.','Ajouter tous les ingrédients, en versant le thé en dernier.','Mélanger délicatement pour bien homogénéiser le cocktail.','Ajuster la quantité de citron et/ou de sucre selon votre goût.','Ajouter de la glace supplémentaire si nécessaire.','Déguster', 6, 5, 12),
('Clear Piña colada', 'La Clear Piña Colada est une version raffinée de la Piña Colada classique. Elle conserve les saveurs emblématiques du cocktail original, mais avec l''ajout de citron et un processus de filtration complète. Cette technique permet de maintenir toutes les nuances tropicales de l''ananas et de la noix de coco, tout en apportant une fraîcheur et une clarté au cocktail. Le résultat est une boisson avec une texture plus légère et moins lourde, offrant une expérience gustative plus rafraîchissante et agréable, sans perdre l''essence de la Piña Colada traditionnelle.', 'Pour réaliser ce cocktail, il est essentiel de prévoir du temps à l''avance. En effet, le processus de filtration peut prendre plusieurs minutes, voire plusieurs heures, pour atteindre la clarté souhaitée. Cette étape est cruciale pour obtenir la texture légère et la fraîcheur caractéristique de la Clear Piña Colada. De plus, ce cocktail se prête parfaitement à être servi en shots, offrant une manière unique et rafraîchissante de déguster cette boisson tropicale classique. La Clear Piña Colada en shot permet de savourer toutes les saveurs exotiques de l''ananas et de la noix de coco, tout en bénéficiant d''une présentation élégante et moderne. Les quantités indiquées sont prévues pour préparer un litre de cocktail. Cependant, il est tout à fait possible de réduire les proportions si vous souhaitez en préparer une quantité moindre. Ajustez simplement les ingrédients en conséquence pour obtenir la quantité désirée, tout en conservant les mêmes proportions pour garantir que les saveurs restent équilibrées et authentiques. Cela permet de personnaliser la recette selon vos besoins, que ce soit pour une petite réunion intime ou une grande fête.', 'En tant que barman, certains cocktails peuvent devenir lassants à force d''en préparer des centaines, voire des milliers chaque jour. C''est dans ce contexte que le barman français Kévin Standaert a cherché à réinventer la Piña Colada. Fatigué de la lourdeur de la crème de coco qui caractérise ce cocktail, il voulait retrouver le goût unique et exotique de la Piña Colada tout en évitant cette texture riche et dense. Ainsi est née la Clear Piña Colada, une version innovante et rafraîchissante qui préserve les saveurs tropicales de l''ananas et de la noix de coco, mais avec une légèreté et une clarté qui rendent le cocktail plus agréable à boire.', 'clear_pina_colada_cocktail.webp', 'Dans un mixing glass, verser les ingrédients sans glace.','Placer un filtre à café dans un entonnoir et positionner l''ensemble au-dessus d''une bouteille ou d''un autre récipient.','Verser le mélange dans l''entonnoir avec le filtre à café et laisser la décoction se filtrer tranquillement.','Une fois le cocktail filtré, verser 150 ml dans un shaker rempli de glace.','Shaker et passer dans le verre avec de la glace.','Déguster.', 1, 6, 2);















INSERT INTO "category" ("name", "description") VALUES ('Classique', 'Les cocktails classiques sont les recettes traditionnelles et intemporelles qui ont souvent été créées dans les années 1800 et au début des années 1900. Exemples: Martini, Old Fashioned, Manhattan, Negroni, Margarita.'),
('Sour', 'Les cocktails sour se caractérisent par une combinaison d''un spiritueux, de jus de citron ou de lime, et de sucre. Réalisé au shaker. Ils peuvent également inclure un blanc d''œuf pour une texture plus soyeuse. Exemples: Whiskey Sour, Pisco Sour, Amaretto Sour, Margarita, Daiquiri.'),
('Fizz', 'Les cocktails fizz sont similaires aux sours mais incluent une touche de soda ou d''eau gazeuse pour une texture pétillante. Servi sans glace. Exemples: Gin Fizz, Vodka Fizz, Ramos Gin Fizz, Sloe Gin Fizz.'),
('Collins', 'Les cocktails Collins sont similaires aux Fizz mais ne sont pas shaké, ils sont réalisés directement au verre sur glace. Exemples: Tom collins, John collins.'),
('Highball', 'Les highballs sont des cocktails simples composés d''un spiritueux et d''un grand volume de mixer, généralement servis dans un verre highball. Exemples: Whiskey Ginger, Cuba Libre, Dark and Stormy, Screwdriver.'),
('Tiki', 'Les cocktails tiki sont des boissons tropicales souvent élaborées avec plusieurs types de rhum, des jus de fruits, des sirops et des bitters, et servis dans des verres ou mugs décoratifs. Exemples: Mai Tai, Zombie, Pina Colada, Blue Hawaiian, Painkiller.'),
('Champagne', 'Les cocktails à base de champagne sont des boissons pétillantes qui utilisent le champagne ou d''autres vins mousseux comme ingrédient principal. Exemples: Mimosa, French 75, Bellini, Kir Royal, Champagne Cocktail.
'),
('Dessert', 'Les cocktails dessert sont des boissons sucrées souvent servies après le repas, parfois avec des ingrédients crémeux ou des saveurs de chocolat et de café. Exemples: Espresso Martini, Brandy Alexander, Grasshopper, Mudslide, White Russian.'),
('Frozen', 'Les cocktails glacés sont préparés en mixant les ingrédients avec de la glace pilée dans un blender, créant une texture similaire à un smoothie. Exemples: Frozen Margarita, Frozen Daiquiri, Piña Colada, Frozen Mudslide.'),
('Bière', 'Les cocktails à base de bière combinent de la bière avec d''autres spiritueux, liqueurs ou jus de fruits. Exemples: Michelada, Black Velvet, Shandy, Beer Margarita, Snakebite.'),
('Chaud', 'Les cocktails chauds sont des boissons servies chaudes, souvent associées à l''hiver et aux fêtes de fin d''année. Exemples: Irish Coffee, Hot Toddy, Mulled Wine, Hot Buttered Rum, Spiked Hot Chocolate.'),
('Low', 'Les cocktails légers en alcool utilisent des ingrédients à faible teneur en alcool, parfaits pour ceux qui souhaitent une boisson plus légère. Exemples: Spritz, Americano, Sherry Cobbler, Vermouth and Soda, Aperol Spritz.'),
('Punch', 'Les punchs sont des boissons préparées en grande quantité et servies dans un bol à punch. Ils peuvent être à base de rhum, de vin, ou d''autres spiritueux, et sont souvent accompagnés de fruits et d''épices. Exemples: Sangria, Planter''s Punch, Rum Punch, Pimm''s Cup, Holiday Punch.'),
('Création', 'Les cocktails de création sont des recettes originales et inventives, souvent créées par des mixologues professionnels ou des amateurs passionnés. Exemples: Gin Basil Smash, Penicillin, Paper Plane, Jungle Bird, Trinidad Sour.'),
('Thé', 'Les cocktails à base de thé utilisent le thé comme ingrédient principal, apportant des saveurs complexes et des arômes subtils.');


INSERT INTO "recipe_ingredient" ("recipe_id", "ingredient_id", "quantity","unit") VALUES (1, 5, 50,'ml'),
(1, 12, 25, 'ml'),
(1, 29, 25, 'ml'),
(2, 19, 60, 'ml'),
(2, 37, 120, 'ml'),
(2, 39, 20, 'ml'),
(2, 43, 1, 'rondelle'),
(3, 45, 1,'tranche'),
(3, 4, 50, 'ml'),
(3, 24, 120, 'ml'),
(3, 33, 50, 'ml'),
(4, 1, 50, 'ml'),
(4, 15, 20, 'ml'),
(4, 36, 1, ''),
(4, 16, 5, 'ml'),
(5, 4, 50, 'ml'),
(5, 29, 20, 'ml'),
(5, 32, 100, 'ml'),
(6, 46, 8, 'feuilles'),
(6, 2, 50, 'ml'),
(6, 29, 20, 'ml'),
(6, 16, 15, 'ml'),
(7, 9, 60, 'ml'),
(7, 16, 20, 'ml'),
(7, 20, 6, 'traits'),
(7, 43, 1, 'zeste'),
(8, 2, 40, 'ml'),
(8, 21, 40, 'ml'),
(8, 40, 30, 'ml'),
(8, 43, 1, 'tranche'),
(9, 13, 50, 'ml'),
(9, 16, 10, 'ml'),
(9, 27, 20, 'ml'),
(9, 35, 20, 'ml'),
(9, 20, 5, 'traits'),
(10, 48, 50, 'ml'),
(10, 49, 10, 'ml'),
(10, 27, 20, 'ml'),
(10, 47, 40, 'ml'),
(10, 35, 20, 'ml'),
(10, 20, 3, 'traits'),
(11, 3, 50, 'ml'),
(11, 29, 20, 'ml'),
(11, 16, 20, 'ml'),
(11, 39, 40, 'ml'),
(11, 31, 8, 'feuilles'),
(12, 3, 50, 'ml'),
(12, 29, 20, 'ml'),
(12, 16, 10, 'ml'),
(12, 51, 50, 'ml'),
(12, 50, 1, 'demi'),
(13, 39, 20, 'ml'),
(13, 23, 60, 'ml'),
(13, 37, 120, 'ml'),
(13, 29, 10, 'ml'),
(13, 30, 3, 'quartiers'),
(13, 31, 6, 'feuilles'),
(14, 4, 50, 'ml'),
(14, 26, 30, 'ml'),
(14, 49, 20, 'ml'),
(14, 29, 30, 'ml'),
(14, 24, 30, 'ml'),
(14, 28, 30, 'ml'),
(15, 52, 40, 'ml'),
(15, 53, 15, 'ml'),
(15, 54, 1, ''),
(15, 2, 50, 'ml'),
(15, 29, 15, 'ml'),
(16, 55, 1, ''),
(16, 56, 50, 'ml'),
(16, 28, 50, 'ml'),
(16, 16, 10, 'ml'),
(16, 29, 20, 'ml'),
(17, 57, 60, 'ml'),
(17, 30, 1, ''),
(17, 16, 20, 'ml'),
(18, 1, 50, 'ml'),
(18, 32, 100, 'ml'),
(18, 29, 20, 'ml'),
(19, 58, 30, 'ml'),
(19, 59, 5, 'traits'),
(19, 60, 100, 'ml'),
(19, 27, 10, 'ml'),
(19, 5, 40, 'ml'),
(20, 5, 40, 'ml'),
(20, 28, 40, 'ml'),
(20, 20, 4, 'traits'),
(20, 29, 20, 'ml'),
(20, 61, 120, 'ml'),
(20, 62, 10, 'ml'),
(21, 4, 250, 'ml'),
(21, 24, 350, 'ml'),
(21, 29, 150, 'ml'),
(21, 33, 150, 'ml'),
(21, 16, 100, 'ml');

INSERT INTO "recipe_ustensil" ("recipe_id", "ustensil_id") VALUES (1,1),
(1, 2),
(1, 4),
(1, 6),
(1, 7),
(2, 2),
(2, 6),
(3, 6),
(3, 9),
(4, 1),
(4, 4),
(4, 6),
(5, 2),
(5, 6),
(5, 7),
(6, 1),
(6, 4),
(6, 5),
(6, 6),
(6, 7),
(6, 9),
(7, 2),
(7, 3),
(7, 4),
(7, 6),
(8, 2),
(8, 6),
(9, 1),
(9, 4),
(9, 6),
(10, 1),
(10, 4),
(10, 6),
(11, 2),
(11, 5),
(11, 6),
(12, 6),
(12, 9),
(13, 2),
(13, 6),
(14, 1),
(14, 4),
(14, 6),
(15, 1),
(15, 4),
(15, 6),
(15, 9),
(16, 1),
(16, 4),
(16, 6),
(16, 8),
(17, 2),
(17, 5),
(18, 2),
(18, 6),
(19, 2),
(19, 6),
(20, 2),
(20, 6),
(21, 1),
(21, 2),
(21, 3),
(21, 4),
(21, 6),
(21, 13);

INSERT INTO "recipe_category" ("recipe_id", "category_id") VALUES (1, 1),
(1, 2),
(2, 1),
(2, 7),
(2, 12),
(3, 1),
(3, 6),
(4, 8),
(5, 5),
(6, 2),
(7, 1),
(8, 1),
(9, 1),
(9, 2),
(10, 14),
(10, 15),
(11, 1),
(12, 9),
(13, 1),
(13, 7),
(13, 12),
(14, 6),
(14, 14),
(15, 14),
(16, 1),
(16, 7),
(17, 1),
(18, 1),
(19, 12),
(19, 14),
(19, 15),
(20, 12),
(20, 14),
(20, 15),
(21, 14);

COMMIT;